
title: sientist astronomer developer musician
title1: Stevan Aleksic

author: Stdubic
email: stevandaleksic@gmail.com
description: Some curious notes, coding and cleverness.

twitter_username: stdubic 
github_username:  stdubic
soundcloud_username: dubic

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
exclude:
  - Gemfile
  - Gemfile.lock
theme: jekyll-theme-hacker

